theme: jekyll-theme-cayman
title: Sentinel
description: A powerful password management disord bot
show_downloads: false
github:
  zip_url: https://github.com/sentinel-pw
  another_url: https://github.com/sentinel-pw
