theme: jekyll-theme-cayman
title: Sentinel
description: A powerful password management disord bot
darkmode: true
logo_url: https://github.com/sentinel-pw/sentinel-discord/blob/main/docs/logo.png
buttons:
      zip_hide: true
      tar_hide: true
      github_hide: false
